import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const res = await fetch('https://worldtimeapi.org/api/timezone/America/New_York', { cache: 'no-cache' } )
  const data = await res.json()
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>{ data.datetime }</p>
        {children}</body>
    </html>
  )
}
